apiVersion: v1
kind: Service
metadata:
  name: ops-agent-service
  namespace: {{ include "hci.namespace" . }}
  labels:
    {{- include "hci.podLabels" (dict "name" "ops-agent-service" "Release" .Release "Chart" .Chart) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
      name: http
  selector:
    {{- include "hci.selectorLabels" (dict "name" "ops-agent-service" "Release" .Release) | nindent 4 }}
