apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fixture.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hci-sim.labels" . | nindent 4 }}
data:
  fixture-manifest.json: |-
{{ .Files.Get .Values.fixture.manifestFile | indent 4 }}
