apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fixture.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hci-sim.labels" . | nindent 4 }}
data:
  {{- range .Values.fixture.manifestFiles }}
  {{ base . }}: |-
{{ $.Files.Get . | indent 4 }}
  {{- end }}
