apiVersion: v1
kind: ResourceQuota
metadata:
  name: hci-sim-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory | quote }}
    pods: {{ .Values.resourceQuota.pods | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: hci-sim-limits
  namespace: {{ .Release.Namespace }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: "1"
        memory: 512Mi
