apiVersion: v1
kind: Service
metadata:
  name: hci-sim
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hci-sim.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "hci-sim.selectorLabels" . | nindent 4 }}
  ports:
    - name: ssh
      port: {{ .Values.service.sshPort }}
      targetPort: ssh
      protocol: TCP
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
