# 环境仓库模板：prod
# 生产环境必须通过审批后更新镜像 tag

global:
  environment: prod

apiGateway:
  image:
    repository: hci-api-gateway
    tag: "latest"

caseService:
  image:
    repository: hci-case-service
    tag: "latest"

conversationService:
  image:
    repository: hci-conversation-service
    tag: "latest"

schedulerService:
  image:
    repository: hci-scheduler-service
    tag: "latest"

kbService:
  image:
    repository: hci-kb-service
    tag: "latest"

customerUI:
  image:
    repository: hci-customer-ui
    tag: "latest"

adminUI:
  image:
    repository: hci-admin-ui
    tag: "latest"
