{{- if .Values.kbService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kb-service
  namespace: {{ include "hci.namespace" . }}
  labels:
    {{- include "hci.podLabels" (dict "name" "kb-service" "Release" .Release "Chart" .Chart) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kbService.port }}
      targetPort: {{ .Values.kbService.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "hci.selectorLabels" (dict "name" "kb-service" "Release" .Release) | nindent 4 }}
{{- end }}
