{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hci-ingress
  namespace: {{ include "hci.namespace" . }}
  labels:
    {{- include "hci.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.global.domain }}
    - host: "api.{{ .Values.global.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: {{ .Values.apiGateway.port }}
    - host: "admin.{{ .Values.global.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-ui
                port:
                  number: {{ .Values.adminUI.port }}
    - host: "{{ .Values.global.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-ui
                port:
                  number: {{ .Values.customerUI.port }}
    {{- else }}
    - http:
        paths:
          # 后端 API
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: {{ .Values.apiGateway.port }}
          # WebSocket
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: {{ .Values.apiGateway.port }}
          # 客户端与管理端（因无 host 路由，fallback 方案只能同时发配至其中一个或用 path 区分。为了后兼容，保留旧版）
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: admin-ui
                port:
                  number: {{ .Values.adminUI.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-ui
                port:
                  number: {{ .Values.customerUI.port }}
    {{- end }}
{{- end }}
